Fix img attributes
okfde/codefor.de pull request #200
Opened 2020-10-03 17:14 UTC by rowbean

added empty alt attributes

2021-01-02 19:24 UTC, ubergesundheit commented on themes/codefor-theme/layouts/shortcodes/ziele/accordion-goals.html
> +									<img class="img-fluid" src="/img/close-icon.svg" alt="">
```suggestion
									<img class="img-fluid" src="/img/close-icon.svg" aria-hidden="true">
```

2021-01-02 19:24 UTC, ubergesundheit commented on themes/codefor-theme/layouts/shortcodes/ziele/accordion-goals.html
> +							<img class="img-fluid p-2" src="/icons/{{ $element.icon }}" alt="">
```suggestion
							<img class="img-fluid p-2" src="/icons/{{ $element.icon }}" aria-hidden="true">
```

2021-01-02 19:29 UTC, wagnerpeer requested changes
I like the idea of adding alt tags. But please try to add descriptive text as intended by using such tags.

2021-01-02 19:29 UTC, wagnerpeer commented on themes/codefor-theme/layouts/shortcodes/ziele/accordion-goals.html
> +									<img class="img-fluid" src="/img/close-icon.svg" alt="">
Why are we using an empty alternative description? I would like to see a real description like "Closing Icon 'X'"

2021-01-02 19:29 UTC, wagnerpeer commented on themes/codefor-theme/layouts/shortcodes/ziele/accordion-goals.html
> +							<img class="img-fluid p-2" src="/icons/{{ $element.icon }}" alt="">
I know, that the icons are picked, based on short codes. However, at least the name of the icon could give a hint if used as alt text.
```html
<img class="img-fluid p-2" src="/icons/{{ $element.icon }}" alt="{{ $element.icon }}">
```

2021-01-03 02:32 UTC, rowbean commented
> 
> 
> I like the idea of adding alt tags. But please try to add descriptive text as intended by using such tags.

I like using alt tags too, but in this case i don't see a content value - https://developer.mozilla.org/en-US/docs/Learn/Accessibility/HTML#Empty_alt_attributes

2021-02-01 18:56 UTC, wagnerpeer approved these changes

2021-08-12 17:39 UTC, iamsilvio commented
Stale PR 
empty alt tags are not helpful

2021-08-12 17:39 UTC, closed without merging