Create 2021-08-12-bodenfeuchtigkeit.md
okfde/codefor.de pull request #285
Opened 2021-08-12 13:00 UTC by micky-m

Neues Projekt für Bielefeld: Bodenfeuchtigkeit im Teutoburger Wald darstellbar machen. Die Idee wird auch bei der Open Innovation City Bielefeld vorgestellt. 

@okfde/codeforde-devs

2021-08-12 17:22 UTC, iamsilvio requested changes

2021-08-12 17:22 UTC, iamsilvio commented on content/projekte/2021-08-12-bodenfeuchtigkeit.md
> +title: Sichtbarmachung von Bodenfeuchtigkeit  im Teutoburger Wald
```suggestion
title: Sichtbarmachung von Bodenfeuchtigkeit im Teutoburger Wald
```

Das Leerzeichen sollte da raus :)

2021-08-12 17:22 UTC, iamsilvio commented on content/projekte/2021-08-12-bodenfeuchtigkeit.md
> +Die Projektidee wird auch im Rahmen der Community der Open Innovation City Bielefeld vorgestellt.
```suggestion
Die Projektidee wird auch im Rahmen der Community der [Open Innovation City Bielefeld](https://openinnovationcity.de) vorgestellt. 
```

2021-08-13 16:06 UTC, micky-m commented
Hab ich die Änderung so richtig im commit aufgenommen?

2021-08-13 16:16 UTC, iamsilvio commented
> Hab ich die Änderung so richtig im commit aufgenommen?

jupp perfekt!

2021-08-13 16:17 UTC, iamsilvio approved these changes

2021-08-13 16:17 UTC, merged