Projektseiten für das ARS-Tool und das LeiKa-Tool hinzugefügt
okfde/codefor.de pull request #317
Opened 2021-12-21 22:46 UTC by codedust

2021-12-22 09:14 UTC, ubergesundheit commented
Kannst du noch das riesige PNG austauschen? Hab es mal mit squoosh.app zum jpg konvertiert
![image](https://user-images.githubusercontent.com/1494211/147067707-ad478bde-5182-4809-9863-a6ccf4aca5cb.jpg)

2021-12-22 09:20 UTC, ubergesundheit requested changes
![image](https://user-images.githubusercontent.com/1494211/147068652-061b3fb5-f0e4-4435-9f47-8670592011ea.png)

Das andere Bild kann auch noch verschlankt werden..

2021-12-23 16:05 UTC, codedust commented
Habe beide Bilder durch jpgs ersetzt.

2021-12-23 16:23 UTC, ubergesundheit approved these changes
Wunderbar :+1:

2021-12-25 12:27 UTC, k-nut commented
@codedust jetzt wo dein anderer PR gemerged wurde ist dieser hier out of date. Könntest du einmal re-basen? Sobald das getan ist können wir gerne mergen :)

2021-12-25 12:54 UTC, merged