Create blogpost for december 2021
okfde/codefor.de pull request #320
Opened 2021-12-30 19:06 UTC by klaraloreen

2022-01-01 10:09 UTC, k-nut commented on content/blog/2021-12-30-out-in-the-open-december-2021.md
> +Hatten wir im letzten Monat noch recht abstrakt einige Artikel über die Nachteile der modernen IT-Infrastruktur verlinkt, die in großen Teilen auf der kaum wertgeschätzten Arbeit von wenigen Open Sou
```suggestion
Hatten wir im letzten Monat noch recht abstrakt einige Artikel über die Nachteile der modernen IT-Infrastruktur verlinkt, die in großen Teilen auf der kaum wertgeschätzten Arbeit von wenigen Open Source Entwickler:innen beruht, erhielt das Thema [mit der Entdeckung der gravierenden Log4j-Schwachstelle](https://www.spiegel.de/netzwelt/web/log4-j-schwachstelle-ja-leute-die-scheisse-brennt-lichterloh-a-760bd03d-42d2-409c-a8d2-d5b13a9150fd) eine sehr konkrete Dimension: Plötzlich wurde Open Source und dessen (mangelnde) Förderung auch in den deutschen Medien [wie der FAZ](https://www.faz.net/aktuell/wirtschaft/digitec/sicherheitsluecke-log4j-was-spricht-fuer-und-gegen-freie-software-17684344.html) oder [dem Bayrischen Rundfunk](https://www.br.de/nachrichten/netzwelt/log4j-sicherheitsluecke-der-ruf-nach-open-source-foerderung,SrZk0fP) diskutiert. Für das Jahr 2022 hegen wir den Wunsch, dass die Debatte über die Wertschätzung Freier Software und Offener Daten noch breiter geführt wird – und das, ohne dafür einen negativen Auslöser wie die Log4j-Schwachstelle zu benötigen.
```

2022-01-01 10:19 UTC, k-nut commented on content/blog/2021-12-30-out-in-the-open-december-2021.md
> +Hatten wir im letzten Monat noch recht abstrakt einige Artikel über die Nachteile der modernen IT-Infrastruktur verlinkt, die in großen Teilen auf der kaum wertgeschätzten Arbeit von wenigen Open Sou
Github zeigt das nicht sonderlich toll an aber hier wird nur einmal aus `Entwicklern` `Entwickler:innen`

2022-01-01 18:03 UTC, johnjohndoe requested changes
Meine 2 cents

2022-01-01 18:32 UTC, tifa365 approved these changes

2022-01-01 18:35 UTC, merged

2022-01-03 09:56 UTC, fnogatz commented on content/blog/2021-12-30-out-in-the-open-december-2021.md
> +Man sollte glauben in der deutschen Hauptstadt sei bereits alles, von Graffiti bis hin zu Flohmärkten, mehrfach kartiert und verbloggt. Aber nein, auch in Berlin befanden sich bis jetzt sich noch wei
An der Stelle heißt es im h2 auch `Uns sonst so?` statt `Und`. Da ich nicht auschließen will, dass das genau so beabsichtigt war, erstmal nur hier als Kommentar statt gleich eines Pull Requests :)

2022-01-03 10:28 UTC, ubergesundheit commented on content/blog/2021-12-30-out-in-the-open-december-2021.md
> +Man sollte glauben in der deutschen Hauptstadt sei bereits alles, von Graffiti bis hin zu Flohmärkten, mehrfach kartiert und verbloggt. Aber nein, auch in Berlin befanden sich bis jetzt sich noch wei
mach ruhig einen PR auf