Out in the open blog post for July 2022
okfde/codefor.de pull request #363
Opened 2022-08-04 22:37 UTC by joergreichert

2022-08-17 09:18 UTC, fnogatz commented
Hm, fehlt hier nur noch das Review, @joergreichert, oder noch was anderes?

2022-08-17 09:23 UTC, joergreichert commented
> Hm, fehlt hier nur noch das Review, @joergreichert, oder noch was anderes?

Ja, genau, nur noch das inhaltliche Review. Den Fehler mit den Leerzeichen bei den Links hatte ich behoben.

2022-08-19 09:14 UTC, johnjohndoe requested changes
Hier meine Funde ...

2022-08-19 09:14 UTC, johnjohndoe commented on content/blog/2022-08-04-out-in-the-open-july-2022.md
> +In Digitransit lassen sich auch Routen mit eigenem Fahrrad oder von Verleihstationen bezogenen Fahrrädern planen. Wie verkehrsssicher diesen Routen sind, sieht man allerdings nicht.
Oben ist "Digitransit" klein geschrieben.
Zu viele "s" in "verkehrssicher"

2022-08-19 09:14 UTC, johnjohndoe commented on content/blog/2022-08-04-out-in-the-open-july-2022.md
> +Im Bereich Energie stehen leider auch noch viele Daten, vor allem auch kleinteilige Verbrauchsdaten, nicht offen zur Verfügung. Auf dem [Dashboard Deutschland](https://www.dashboard-deutschland.de/en
"verdeutlicht" fehlt ein "t"
Komma nach "Dashboard Deutschland" statt Punkt?

2022-08-19 09:14 UTC, johnjohndoe commented on content/blog/2022-08-04-out-in-the-open-july-2022.md
> +Schlimmer ist nur noch die Lizenzierung von Mobilitäts-Daten in Österreich: "Für grobe Verstöße \[…\] wird je Verstoß eine Vertragsstrafe in Höhe von EUR 20.000,- vereinbart.", wie [Julius](https://t
Bitte ohne Bindestrich

2022-08-19 10:07 UTC, saerdnaer commented on content/blog/2022-08-04-out-in-the-open-july-2022.md
> +Im Bereich Energie stehen leider auch noch viele Daten, vor allem auch kleinteilige Verbrauchsdaten, nicht offen zur Verfügung. So enthält das [Dashboard Deutschland](https://www.dashboard-deutschlan
```suggestion
Im Bereich Energie stehen leider auch noch viele Daten nicht offen zur Verfügung, vor allem auch kleinteilige Verbrauchsdaten. So enthält das [Dashboard Deutschland](https://www.dashboard-deutschland.de/energie/energie) nur stark aggregierte Statistiken und im [Marktstammdatenregister](https://www.marktstammdatenregister.de/MaStR/Einheit/Einheiten/OeffentlicheEinheitenuebersicht) sieht man zwar, wie der Name sagt, Stammdaten zu Einheiten (z.B. Energiespeicher, Solaranlagen) und Akteuren (z.B. Anlagenbetreiber), die tatsächlichen Einspeise- und Verbrauchsdaten aber nicht. Für die intelligente dezentrale Stromerzeugung und -nutzung bräuchte man eben diese Daten gesammelt, wie der Artikel [Die Energiewelt von Morgen](https://handbuch-ki.net/die-energiewelt-von-morgen/) bereits 2019 im Handbuch KI mit konkretem Anwendungsfall verdeutlicht.
```

2022-08-19 10:07 UTC, saerdnaer commented on content/blog/2022-08-04-out-in-the-open-july-2022.md
> +### Neue Offene Datensätzen
```suggestion
### Neue Offene Datensätze
```

2022-08-19 10:07 UTC, saerdnaer commented on content/blog/2022-08-04-out-in-the-open-july-2022.md
> +Fund von [Tobias](https://twitter.com/tobwen/status/1546459976612315138): Das BKG erlaubt über eine Zusatzvereinbarung nun auch, die von ihm unter der "Datenlizenz Deutschland mit Namensnennung" (DL-
```suggestion
Fund von [Tobias](https://twitter.com/tobwen/status/1546459976612315138): Das BKG erlaubt über eine Zusatzvereinbarung nun auch, die von ihm unter der "Datenlizenz Deutschland mit Namensnennung" (DL-DE/BY-2-0) veröffentlichten Datensätze für OpenStreetMap zu verwenden - die Referenz auf die Quelle im Changeset der OpenStreetMap-Bearbeitung reicht aus. Das klingt auf den ersten Blick gut, zeigt aber nur einmal mehr, dass die kurz und knapp verfassten DL-DE-Lizenzen mehr Rechtsunsicherheiten geschaffen haben als sie ausräumen.
```

2022-08-19 10:08 UTC, saerdnaer approved these changes
Ansonsten LGTM.

2022-08-19 10:21 UTC, johnjohndoe requested changes
Hier noch ein paar Funde meiner Zugbegleitung ...

2022-08-19 10:21 UTC, johnjohndoe commented on content/blog/2022-08-04-out-in-the-open-july-2022.md
> +Auch das zivilgesellschaftlich betriebene [bund.dev](https://bund.dev) lebt eine entsprechende OpenSource-Kultur vor. So wurde nun nach Rücksprache auch die offiziellen Informationen zu den Nutzungsb
"wurde"fehlt ein "n"

2022-08-19 10:21 UTC, johnjohndoe commented on content/blog/2022-08-04-out-in-the-open-july-2022.md
> +Laut der [Visualisierung des statistischen Bundesamtes](https://www.destatis.de/DE/Presse/Pressemitteilungen/2022/07/PD22_284_12.html) gab es deutlich mehr Bahnreisen zwischen 30 und 300 Kilometern i
"bundesweiten", "n" muss weg

2022-08-19 10:21 UTC, johnjohndoe commented on content/blog/2022-08-04-out-in-the-open-july-2022.md
> +In digitransit lassen sich auch Routen mit eigenem Fahrrad oder von Verleihstationen bezogenen Fahrrädern planen. Wie verkehrssicher diesen Routen sind, sieht man allerdings nicht.
"diesen Routen", "n" bei "diesen" muss weg

2022-08-19 10:21 UTC, johnjohndoe commented on content/blog/2022-08-04-out-in-the-open-july-2022.md
> +FragDenStaat hatte einst 2019 [offeneregister.de](https://offeneregister.de/) im Rahmen einer Kampagne aufgesetzt, um eben auf der Fehlen eines offenen Zugangs hinzuweisen und zu demonstrieren, wie d
"das" statt "der Fehlen"

2022-08-19 10:21 UTC, johnjohndoe commented on content/blog/2022-08-04-out-in-the-open-july-2022.md
> +Einen erste Anwendung, die diese Daten mit Straßendaten aus dem Geoportal verknüpft, gibt es [schon](https://twitter.com/linkedktk/status/1551606197438087168).
"Einen" = "n" am Ende weg

2022-08-19 10:45 UTC, johnjohndoe approved these changes
🚢 it

2022-08-19 11:22 UTC, johnjohndoe approved these changes

2022-08-21 06:01 UTC, joergreichert commented
@k-nut inhaltliche Reviews sind durch, fehlt nur der finale Merge durch jemanden aus der codeforde-devs Gruppe

2022-08-21 21:38 UTC, johnjohndoe commented
@joergreichert Was ist mit dem fehlschlagenden percy/codefor.de Check?

2022-08-22 05:31 UTC, k-nut commented
Der Percy Check schlägt unter anderem fehl, weil die Header Items ihren Active State verlieren. Aktuell wird z.b. Blog unterstrichen, wenn man sich auf einer Blog (Unter-)Seite befindet, in der neuen Version nicht mehr. Ich würde mal vermuten, dass das am Hugo Upgrade liegt. Warum hattest du denn hier die Version hochgezogen @joergreichert? Und könnten wir das vielleicht unabhängig von dem neuen Blogpost behandeln?

2022-08-22 08:29 UTC, joergreichert commented
Ich habe die Hugo-Version nochmal zurückgerollt, das liegt aber tatsächlich nicht daran, sondern an der Änderung bei render_link.html - https://github.com/okfde/codefor.de/pull/363/files#diff-ba8f97bf8114cd26fa037acc97ff5b9fb456dfcb75c3273af23cc7d404c6112a   Durch den nun fehlenden Zeilenumbruch wird jetzt der Underline nicht mehr dargestellt. Wenn der Zeilenumbruch wieder da wäre, würden aber alle Links in den Texten ein trailing whitespace bekommen (was bei Punkten und Kommas echt blöd aussieht, vor allem, wenn sie auf die nächste Zeile rutschen). Wahrscheinlich macht das dann eher Sinn die Navigations-Links als html-Elemente im markdown direkt anzugeben?

2022-08-22 16:29 UTC, joergreichert commented
@k-nut wie wollen wir weiter vorgehen. Ich kann die Links im Blog-Post auch alle als <a href ></a> definieren und rolle die Änderungen an der render_links.html wieder zurück.

2022-08-23 04:59 UTC, k-nut commented
@joergreichert ich hab jetzt auch noch mal die Änderungen an der netlify Config zurückgerollt und denke, dass jetzt gut aussieht. Bei percy hab ich es jetzt auch approved.

2022-08-23 04:59 UTC, k-nut approved these changes

2022-08-23 05:00 UTC, k-nut commented
Ich merge den Beitrag jetzt mal. Danke noch mal für für deine ganze Arbeit Jörg!

2022-08-23 05:00 UTC, merged

2022-08-23 06:44 UTC, joergreichert commented
Ah, die Änderung in der Netlify-Config habe ich übersehen, dann lag es doch an der Hugo-Version. Danke fürs Fixen und Mergen.