WIP: Add `Spenden` page
okfde/codefor.de pull request #430
Opened 2023-06-12 09:02 UTC by k-nut

2023-06-12 14:09 UTC, sonjafischbauer commented on content/spenden.md
> +### Überweisung
change Headline to: 
### Spenden via Überweisung

2023-06-12 14:31 UTC, k-nut commented
@sonjafischbauer deine Änderungswünsche sind alle übernommen :)

2023-06-12 14:56 UTC, sonjafischbauer requested changes
Ich bin durch - bitte verzeih, dass ich es anfangs so stückchenweise gemacht habe. 
Ich habe einige meiner ersten Kommentare nochmal editiert. Bitte verzeih die Verwirrung, die ich dadurch verursacht habe.

2023-06-17 09:01 UTC, k-nut commented on content/spenden.md
> +Community-Veranstaltungen
Changed ✅

2023-06-17 09:01 UTC, k-nut commented on content/spenden.md
> +Unsere Bankverbindung für direkte Spenden oder Überweisungen und Daueraufträge ist:
Changed ✅

2023-06-22 06:01 UTC, joergreichert approved these changes

2023-06-22 06:02 UTC, merged