update projects and lab descriptions and added new project
okfde/codefor.de pull request #444
Opened 2023-08-09 06:13 UTC by p3t3r67x0

2023-08-12 18:17 UTC, joergreichert requested changes
see my comments inline

2023-08-12 18:17 UTC, joergreichert commented on content/labs/flensburg.md
> +Wir sind eine Gruppe von ehrenamtlich Aktiven, mit Expertise in Datenverarbeitung, UI/UX Design, Softwareentwicklung, Stadtplanung, Verwaltung und Datenjournalismus. Wir setzen engagieren uns für meh
```suggestion
Wir sind eine Gruppe von ehrenamtlich Aktiven mit Expertise in Datenverarbeitung, UI/UX Design, Softwareentwicklung, Stadtplanung, Verwaltung und Datenjournalismus. Wir engagieren uns für mehr Transparenz von Behördendaten. Wir machen aus offen Daten nutzerfreundliche Visualisierungen, Geoinformations-Anwendungen und Hardware-Projekte zur Messung von Umweltdaten. Wir treffen uns regelmäßig und lernen von einander und arbeiten an den Projekten. Wir erstellen gemeinsam Anwendungen aus offenen Behördendaten mit dem Ziel mehr Beteiligung zu fördern und Transparenz in Verwaltungen zu etablieren.
```

2023-08-12 18:17 UTC, joergreichert commented on content/projekte/2023-04-29-fl-open-trees-map.md
> +Im ersten Schritt haben wir einen vorhandenen Daten der Straßenbäume der Stadt Flensburg genutzt, um eine einfache Darstellung auf der Karte als Transparente Anlaufstelle für Interesierte zu schaffen
```suggestion
Im ersten Schritt haben wir einen vorhandenen Datensatz der Straßenbäume der Stadt Flensburg genutzt, um eine einfache Darstellung auf der Karte als transparente Anlaufstelle für Interessierte zu schaffen. Hier oben im Norden machen sich klimatische Wetterveränderungen besonders bemerkbar. Deshalb stellen wir uns die folgenden Fragen:
```

2023-08-12 18:17 UTC, joergreichert commented on content/projekte/2023-08-08-fl-open-surface-map.md
> +Diese interaktive Karte zeigt die Verteilung der verschiedenen Flächennutzungsarten beim klick auf die entsprechende Gemeinde an. So lässt sich in Kürze herausfinden in welchen Regionen der Waldfläch
```suggestion
Diese interaktive Karte zeigt die Verteilung der verschiedenen Flächennutzungsarten beim Klick auf die entsprechende Gemeinde an. So lässt sich in Kürze herausfinden in welchen Regionen der Waldflächenanteil besonders hoch ist. Dies ist ein erster Prototyp, welcher mit mehr Filter-Möglichkeiten ausgebaut werden soll. Zudem wollen wir auch die Daten der kreisfreien Städte und Stadtstaaten mit aufnehmen.
```

2023-08-12 18:17 UTC, joergreichert commented on static/projects/flensburg/screenshot_social_map.png
maybe try to get file size also around 150 KB like the baumkataster_stadt_flensburg.png ?

2023-08-12 18:17 UTC, joergreichert commented on static/projects/flensburg/screenshot_surface_map.png
maybe try to get file size also around 150 KB like the baumkataster_stadt_flensburg.png ?

2023-08-12 18:17 UTC, joergreichert commented on static/projects/flensburg/spielplaetze_in_flensburg.png
maybe try to get file size also around 150 KB like the baumkataster_stadt_flensburg.png ?

2023-08-12 18:17 UTC, joergreichert commented on content/projekte/2023-04-29-fl-open-trees-map.md
> +title: Straßebäume der Stadt Flensburg
```suggestion
title: Straßenbäume der Stadt Flensburg
```

2023-08-14 07:02 UTC, digital-codes commented
What about importing lab projects?

2023-08-14 09:24 UTC, p3t3r67x0 commented
@joergreichert thank you for your kind review, just commited suggested changes and reduced file size from screenshots
@digital-codes just added flag to showcase lab projects in overview
@all happy to get merged or feedback

2023-08-15 07:32 UTC, joergreichert approved these changes

2023-08-15 07:34 UTC, merged